// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM-GK-pGIiYighJoH5WwR10yK-knvYb40',
    appId: '1:71214705142:web:88028d653ff856bf8d3fd7',
    messagingSenderId: '71214705142',
    projectId: 'temple-app-f2402',
    authDomain: 'temple-app-f2402.firebaseapp.com',
    storageBucket: 'temple-app-f2402.firebasestorage.app',
    measurementId: 'G-TKHQX8Z6BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTPLCpNN8mXHab41sSOpkXWGU8q6qOPjc',
    appId: '1:71214705142:android:8134c604b86513368d3fd7',
    messagingSenderId: '71214705142',
    projectId: 'temple-app-f2402',
    storageBucket: 'temple-app-f2402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLcm2jxNyTtGhYRVhWmJ1O6mCgWt27pco',
    appId: '1:71214705142:ios:42ad1fd65e706a8f8d3fd7',
    messagingSenderId: '71214705142',
    projectId: 'temple-app-f2402',
    storageBucket: 'temple-app-f2402.firebasestorage.app',
    iosBundleId: 'in.orgspace.ambalpady',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLcm2jxNyTtGhYRVhWmJ1O6mCgWt27pco',
    appId: '1:71214705142:ios:42ad1fd65e706a8f8d3fd7',
    messagingSenderId: '71214705142',
    projectId: 'temple-app-f2402',
    storageBucket: 'temple-app-f2402.firebasestorage.app',
    iosBundleId: 'in.orgspace.ambalpady',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM-GK-pGIiYighJoH5WwR10yK-knvYb40',
    appId: '1:71214705142:web:28eb41097d14f19d8d3fd7',
    messagingSenderId: '71214705142',
    projectId: 'temple-app-f2402',
    authDomain: 'temple-app-f2402.firebaseapp.com',
    storageBucket: 'temple-app-f2402.firebasestorage.app',
    measurementId: 'G-GZV5JGTW7D',
  );

}